version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: weekly
    labels: [dependencies]

updates:
  - package-ecosystem: cargo
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: all-dependencies
