[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
flate2 = "1.1.5"
ignore.workspace = true
tar = "0.4.44"
tempfile = "3.27.0"
syn = { version = "2.0.106", features = ["full", "visit"] }

[dev-dependencies]


[lints]
workspace = true
