//! Stable diagnostic spellings for action-backed UI intentions.

use super::ShortcutActionId;

impl ShortcutActionId {
    #[expect(
        clippy::too_many_lines,
        reason = "the exhaustive spelling replaces derived Debug output in a versioned contract"
    )]
    pub(in crate::ui::shortcut_registry) const fn diagnostic_variant(self) -> &'static str {
        #[allow(
            clippy::enum_glob_use,
            reason = "the exhaustive closed enum mapping is clearer without repeated qualifiers"
        )]
        use ShortcutActionId::*;
        match self {
            New => "New",
            RenameSession => "RenameSession",
            CopySessionId => "CopySessionId",
            CopyResume => "CopyResume",
            SendSession => "SendSession",
            SendSessionRemove => "SendSessionRemove",
            Edit => "Edit",
            PlainNewline => "PlainNewline",
            JumpUp => "JumpUp",
            JumpDown => "JumpDown",
            SelectVisualRowStart => "SelectVisualRowStart",
            SelectVisualRowEnd => "SelectVisualRowEnd",
            ThoughtStart => "ThoughtStart",
            ThoughtEnd => "ThoughtEnd",
            Indent => "Indent",
            Outdent => "Outdent",
            SplitThought => "SplitThought",
            ExtractSelection => "ExtractSelection",
            MergeThoughts => "MergeThoughts",
            Delete => "Delete",
            SubmitRemove => "SubmitRemove",
            SubmitToAgent => "SubmitToAgent",
            SubmitAllRemove => "SubmitAllRemove",
            SubmitAllKeep => "SubmitAllKeep",
            RefreshAgents => "RefreshAgents",
            RefreshAttachments => "RefreshAttachments",
            InsertInvocation => "InsertInvocation",
            RefreshInvocations => "RefreshInvocations",
            CheckUpdates => "CheckUpdates",
            WhatsNew => "WhatsNew",
            ScreenshotInbox => "ScreenshotInbox",
            RetryScreenshotCapture => "RetryScreenshotCapture",
            RetryStorage => "RetryStorage",
            ExportRecovery => "ExportRecovery",
            MoveUp => "MoveUp",
            MoveDown => "MoveDown",
            Collapse => "Collapse",
            Select => "Select",
            RangeSelect => "RangeSelect",
            Help => "Help",
            Quit => "Quit",
            Close => "Close",
            Confirm => "Confirm",
            Backspace => "Backspace",
            DeleteForward => "DeleteForward",
            Tab => "Tab",
            BackTab => "BackTab",
            FocusPrevious => "FocusPrevious",
            FocusNext => "FocusNext",
            ExtendPrevious => "ExtendPrevious",
            ExtendNext => "ExtendNext",
            FastPrevious => "FastPrevious",
            FastNext => "FastNext",
            FastExtendPrevious => "FastExtendPrevious",
            FastExtendNext => "FastExtendNext",
            FocusFirst => "FocusFirst",
            FocusLast => "FocusLast",
            ExtendFirst => "ExtendFirst",
            ExtendLast => "ExtendLast",
            MoveGraphemeBack => "MoveGraphemeBack",
            MoveGraphemeForward => "MoveGraphemeForward",
            MoveWordBack => "MoveWordBack",
            MoveWordForward => "MoveWordForward",
            MoveDocumentStart => "MoveDocumentStart",
            MoveDocumentEnd => "MoveDocumentEnd",
            MoveVisualUp => "MoveVisualUp",
            MoveVisualDown => "MoveVisualDown",
            MoveLineStart => "MoveLineStart",
            MoveLineEnd => "MoveLineEnd",
            ExtendGraphemeBack => "ExtendGraphemeBack",
            ExtendGraphemeForward => "ExtendGraphemeForward",
            ExtendWordBack => "ExtendWordBack",
            ExtendWordForward => "ExtendWordForward",
            ExtendVisualUp => "ExtendVisualUp",
            ExtendVisualDown => "ExtendVisualDown",
            ExtendDocumentStart => "ExtendDocumentStart",
            ExtendDocumentEnd => "ExtendDocumentEnd",
            ExtendLineStart => "ExtendLineStart",
            ExtendLineEnd => "ExtendLineEnd",
            ExtendVisualRowStart => "ExtendVisualRowStart",
            ExtendVisualRowEnd => "ExtendVisualRowEnd",
            MoveVisualRowStart => "MoveVisualRowStart",
            MoveVisualRowEnd => "MoveVisualRowEnd",
            Copy => "Copy",
            Cut => "Cut",
            PasteExact => "PasteExact",
            PasteReflow => "PasteReflow",
            ReflowThought => "ReflowThought",
            InsertAbove => "InsertAbove",
            InsertBelow => "InsertBelow",
            SelectAll => "SelectAll",
            Duplicate => "Duplicate",
            Undo => "Undo",
            Redo => "Redo",
            SubmitKeep => "SubmitKeep",
            DeleteLogicalLine => "DeleteLogicalLine",
            DeleteSentence => "DeleteSentence",
            PickerPrevious => "PickerPrevious",
            PickerNext => "PickerNext",
            ContextualTransform => "ContextualTransform",
            OpenSearch => "OpenSearch",
            OpenCommands => "OpenCommands",
            BrowserTrash => "BrowserTrash",
            ChooseLeft => "ChooseLeft",
            ChooseDown => "ChooseDown",
            ChooseUp => "ChooseUp",
            ChooseRight => "ChooseRight",
        }
    }
}
