//! Closed command-palette vocabulary and canonical visible labels.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(in crate::ui::app) enum Command {
    New,
    RenameSession,
    CopySessionId,
    CopyResume,
    SendSession,
    SendSessionRemove,
    Edit,
    PlainNewline,
    DeleteLogicalLine,
    DeleteSentence,
    JumpUp,
    JumpDown,
    SelectVisualRowStart,
    SelectVisualRowEnd,
    ThoughtStart,
    ThoughtEnd,
    Indent,
    Outdent,
    SplitThought,
    ExtractSelection,
    MergeThoughts,
    Delete,
    Copy,
    Cut,
    Paste,
    Duplicate,
    SelectAll,
    SubmitRemove,
    SubmitKeep,
    SubmitAllRemove,
    SubmitAllKeep,
    RefreshAgents,
    RefreshAttachments,
    InsertInvocation,
    RefreshInvocations,
    CheckUpdates,
    WhatsNew,
    ScreenshotInbox,
    RetryScreenshotCapture,
    RetryStorage,
    ExportRecovery,
    Undo,
    Redo,
    MoveUp,
    MoveDown,
    Collapse,
    Select,
    RangeSelect,
    Help,
    Quit,
}

impl Command {
    pub(super) const ALL: [(Self, &'static str); 50] = [
        (Self::New, "New thought"),
        (Self::RenameSession, "Rename session"),
        (Self::CopySessionId, "Copy session ID"),
        (Self::CopyResume, "Copy resume command"),
        (Self::Edit, "Edit thought"),
        (Self::PlainNewline, "Insert plain newline"),
        (Self::DeleteLogicalLine, "Delete logical line"),
        (Self::DeleteSentence, "Delete sentence"),
        (Self::JumpUp, "Jump cursor up 5 visual rows"),
        (Self::JumpDown, "Jump cursor down 5 visual rows"),
        (
            Self::SelectVisualRowStart,
            "Extend selection to visual row start",
        ),
        (
            Self::SelectVisualRowEnd,
            "Extend selection to visual row end",
        ),
        (Self::ThoughtStart, "Move cursor to thought beginning"),
        (Self::ThoughtEnd, "Move cursor to thought end"),
        (Self::Indent, "Indent line or selection"),
        (Self::Outdent, "Outdent line or selection"),
        (Self::SplitThought, "Split thought at cursor"),
        (Self::ExtractSelection, "Extract selection as new thought"),
        (Self::MergeThoughts, "Merge selected thoughts"),
        (Self::Delete, "Delete thought"),
        (Self::Copy, "Copy thought"),
        (Self::Cut, "Cut thought"),
        (Self::Paste, "Paste native clipboard"),
        (Self::Duplicate, "Duplicate thought or selection"),
        (Self::SelectAll, "Select all thoughts"),
        (Self::SubmitRemove, "Submit"),
        (Self::SubmitKeep, "Submit and keep"),
        (Self::SubmitAllRemove, "Submit all"),
        (Self::SubmitAllKeep, "Submit all and keep"),
        (Self::SendSession, "Send to another Proqi session"),
        (
            Self::SendSessionRemove,
            "Send to another Proqi session and remove thought",
        ),
        (Self::RefreshAgents, "Refresh adjacent agents"),
        (Self::RefreshAttachments, "Refresh attachments"),
        (Self::InsertInvocation, "Insert discovered invocation"),
        (Self::RefreshInvocations, "Refresh invocations"),
        (Self::CheckUpdates, "Check for updates"),
        (Self::WhatsNew, "What's new"),
        (Self::ScreenshotInbox, "Enable Screenshot Inbox"),
        (Self::RetryScreenshotCapture, "Retry Screenshot Capture"),
        (Self::RetryStorage, "Retry failed save"),
        (Self::ExportRecovery, "Export recovery file"),
        (Self::Undo, "Undo board action"),
        (Self::Redo, "Redo board action"),
        (Self::MoveUp, "Move thought up"),
        (Self::MoveDown, "Move thought down"),
        (Self::Collapse, "Expand or collapse thought"),
        (Self::Select, "Toggle thought selection"),
        (Self::RangeSelect, "Start contiguous range selection"),
        (Self::Help, "Open contextual help"),
        (Self::Quit, "Quit Proqi"),
    ];
}
